In [58]:
import pandas as pd
import pickle
import numpy as np

In [59]:
# path changes. 
with open('/home/jtl/Documents/travel_modeling_nhts/outputs/model_summaries.pickle', 'rb') as h:
    model_summaries = pickle.load(h)

In [60]:
for model_path, model in model_summaries:
    helper = model_path.split("_")
    output_var = "_".join(helper[:-1])
    input_structure = helper[-1].split(".")[0]
    
    print(output_var)
    print(input_structure)

HHVEHCNT_P_CAP_mean_norm
BE and NHTS linear
HHVEHCNT_P_CAP_mean_norm
BE and NHTS quadratic
HHVEHCNT_P_CAP_mean_norm
BE linear
HHVEHCNT_P_CAP_mean_norm
BE quadratic
HHVEHCNT_P_CAP_mean_norm
NHTS linear
HHVEHCNT_P_CAP_mean_norm
NHTS quadratic
HHVEHCNT_mean_norm
BE and NHTS linear
HHVEHCNT_mean_norm
BE and NHTS quadratic
HHVEHCNT_mean_norm
BE linear
HHVEHCNT_mean_norm
BE quadratic
HHVEHCNT_mean_norm
NHTS linear
HHVEHCNT_mean_norm
NHTS quadratic
TRPTRANS_1_mean_norm
BE and NHTS linear
TRPTRANS_1_mean_norm
BE and NHTS quadratic
TRPTRANS_1_mean_norm
BE linear
TRPTRANS_1_mean_norm
BE quadratic
TRPTRANS_1_mean_norm
NHTS linear
TRPTRANS_1_mean_norm
NHTS quadratic
TRPTRANS_2_mean_norm
BE and NHTS linear
TRPTRANS_2_mean_norm
BE and NHTS quadratic
TRPTRANS_2_mean_norm
BE linear
TRPTRANS_2_mean_norm
BE quadratic
TRPTRANS_2_mean_norm
NHTS linear
TRPTRANS_2_mean_norm
NHTS quadratic
TRPTRANS_3_mean_norm
BE and NHTS linear
TRPTRANS_3_mean_norm
BE and NHTS quadratic
TRPTRANS_3_mean_norm
BE linear
TRPTRANS_3_mean_norm
BE quadratic
TRPTRANS_3_mean_norm
NHTS linear
TRPTRANS_3_mean_norm
NHTS quadratic

In [61]:
model_path, model = next(iter(model_summaries))

In [62]:
results_as_html = model.tables[1].as_html()
model_df = pd.read_html(results_as_html, header=0, index_col=0)[0]

In [63]:
model_df

           coef   std err       t  P>|t|    [0.025    0.975]
const  1.178000  0.177000   6.669  0.000  0.832000  1.524000
x1     0.000500  0.001000   0.459  0.646 -0.002000  0.002000
x2    -0.461700  0.012000 -39.378  0.000 -0.485000 -0.439000
x3     0.003000  0.000000  12.041  0.000  0.002000  0.003000
x4    -0.114300  0.066000  -1.727  0.084 -0.244000  0.015000
x5     0.000008  0.000004   2.326  0.020  0.000001  0.000015
x6    -0.000060  0.000004 -13.838  0.000 -0.000069 -0.000052
x7    -0.444700  0.048000  -9.255  0.000 -0.539000 -0.351000
x8     0.019300  0.041000   0.471  0.638 -0.061000  0.100000
x9    -0.109700  0.032000  -3.397  0.001 -0.173000 -0.046000
x10    0.236100  0.147000   1.607  0.108 -0.052000  0.524000
x11   -0.266000  0.149000  -1.785  0.074 -0.558000  0.026000
x12    0.352600  0.042000   8.438  0.000  0.271000  0.434000
x13   -0.089100  0.031000  -2.885  0.004 -0.150000 -0.029000
x14   -0.024800  0.037000  -0.676  0.499 -0.097000  0.047000
x15   -0.026600  0.038000  -0.699  0.485 -0.101000  0.048000
x16   -0.116100  0.076000  -1.535  0.125 -0.264000  0.032000
x17   -0.015900  0.030000  -0.527  0.598 -0.075000  0.043000
x18   -0.293900  0.101000  -2.911  0.004 -0.492000 -0.096000

In [64]:
# Here is the key. We need to combine information to TWO columns for each model!
coeff_list = []
std_list = []
for i in range(model_df.shape[0]):
    # coef
    base_coef = '{:.3f}'.format(np.round(model_df['coef'].values[i], decimals = 3))
    if model_df['P>|t|'].values[i] < 0.01:
        base_coef=base_coef+"***"
    elif model_df['P>|t|'].values[i] < 0.05:
        base_coef=base_coef+"**"
    elif model_df['P>|t|'].values[i] < 0.1:
        base_coef=base_coef+"*"
    coeff_list.append(base_coef)
    # std
    base_std = '{:.3f}'.format(np.round(model_df['std err'].values[i], decimals = 3))
    base_std = '('+base_std+')'
    std_list.append(base_std)

# new model report    
new_model_report = pd.DataFrame([coeff_list, std_list], index = ['coef', 'std']).T

In [65]:
new_model_report

         coef      std
0    1.178***  (0.177)
1       0.000  (0.001)
2   -0.462***  (0.012)
3    0.003***  (0.000)
4     -0.114*  (0.066)
5     0.000**  (0.000)
6   -0.000***  (0.000)
7   -0.445***  (0.048)
8       0.019  (0.041)
9   -0.110***  (0.032)
10      0.236  (0.147)
11    -0.266*  (0.149)
12   0.353***  (0.042)
13  -0.089***  (0.031)
14     -0.025  (0.037)
15     -0.027  (0.038)
16     -0.116  (0.076)
17     -0.016  (0.030)
18  -0.294***  (0.101)