# Preprocessing NHTS and Images

In [ ]:
!pip install opencv-python

In [1]:
import numpy as np
import pandas as pd
import cv2
import os
import matplotlib.pyplot as plt
import pickle
import copy
from sklearn.preprocessing import normalize
from sklearn.preprocessing import OneHotEncoder
import skimage.io as io
import sys
import util

import random

In [2]:
# read two csv files and merge them.
df_nhts = pd.read_csv("~/Documents/shenhao/sat_image_nhts/code/data_initial/raw/data_input_V1.csv")
df_loc = pd.read_csv("~/Documents/shenhao/sat_image_nhts/code/data_initial/raw/hhct.csv")

###
#df_nhts = pd.read_csv("data/data_input_V1.csv")
#df_loc = pd.read_csv("data/hhct.csv")
# drop one col
df_loc.drop('HHSTFIPS', axis = 1, inplace = True)

# augment HHCT to df_nhts
df = pd.merge(df_nhts, df_loc, on = 'HOUSEID')

In [3]:
# Create census tract ID by combining columns.
# HHSTFIPS: 2 digits; HHCNTYFP: 3 digits; HHCT: 6 digits. Add zeros in front.
df['HHSTFIPS'] = df['HHSTFIPS'].astype(np.str)
df['HHCNTYFP'] = df['HHCNTYFP'].astype(np.str)
df['HHCT'] = df['HHCT'].astype(np.str)

# HHSTFIPS
df['HHSTFIPS_raw'] = df['HHSTFIPS']
df['HHSTFIPS'].loc[df['HHSTFIPS'].str.len() == 1, ] = '0' + df['HHSTFIPS'].loc[df['HHSTFIPS'].str.len() == 1, ]
# HHCNTYFP
for i in range(2): # 2 = 3-1
    augmented_zero_str = '0' * (i+1)
    df['HHCNTYFP'].loc[df['HHCNTYFP'].str.len() == 2-i, ] = augmented_zero_str + df['HHCNTYFP'].loc[df['HHCNTYFP'].str.len() == 2-i, ]
# HHCT
for i in range(5): # 5 = 6-1
    augmented_zero_str = '0' * (i+1)
    df['HHCT'].loc[df['HHCT'].str.len() == 5-i, ] = augmented_zero_str + df['HHCT'].loc[df['HHCT'].str.len() == 5-i, ]
# Create the census tract identifier
df['CENSUS_ID'] = df['HHSTFIPS'] + df['HHCNTYFP'] + df['HHCT']
# create GEOID for visualization with census tract shapefiles
df['GEOID'] = df['HHSTFIPS_raw'] + df['HHCNTYFP'] + df['HHCT']

/home/jtl/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

## Edit dependent variables (travel behavior variables)

In [4]:
# TRPTRANS
# 0 other
# 1 walk and bike
# 2 car, suv, van, and truck
# 3 public trans
df["TRPTRANS"].values[(df["TRPTRANS"] == 1) | (df["TRPTRANS"] == 2)] = 1
df["TRPTRANS"].values[(df["TRPTRANS"] == 3) | (df["TRPTRANS"] == 4) | (df["TRPTRANS"] == 5) | (df["TRPTRANS"] == 6)] = 2
df["TRPTRANS"].values[(df["TRPTRANS"] == 10) | (df["TRPTRANS"] == 11) | (df["TRPTRANS"] == 14) | (df["TRPTRANS"] == 15) | (df["TRPTRANS"] == 16) | (df["TRPTRANS"] == 12)] = 3
df["TRPTRANS"].values[(df["TRPTRANS"] == 7) | (df["TRPTRANS"] == 8) | (df["TRPTRANS"] == 9)
                      | (df["TRPTRANS"] == 13) | (df["TRPTRANS"] == 17)| (df["TRPTRANS"] == 18) | (df["TRPTRANS"] == 19) 
                      | (df["TRPTRANS"] == 20) | (df["TRPTRANS"] == 97)] = 0

# TRIPPURP
# {'HBO', 'HBSHOP', 'HBSOCREC', 'HBW', 'NHB'}
# {0,1,2,3,4}
df["TRIPPURP"].values[df["TRIPPURP"] == "HBO"] = 0
df["TRIPPURP"].values[df["TRIPPURP"] == "HBSHOP"] = 1
df["TRIPPURP"].values[df["TRIPPURP"] == "HBSOCREC"] = 2
df["TRIPPURP"].values[df["TRIPPURP"] == "HBW"] = 3
df["TRIPPURP"].values[df["TRIPPURP"] == "NHB"] = 4
df["TRIPPURP"].values[df["TRIPPURP"] == "-9"] = -9

In [5]:
# print
print(np.unique(df.TRPTRANS, return_counts=True))
print(list(np.unique(df.TRIPPURP, return_counts=True)))

(array([0, 1, 2, 3]), array([ 13624,  59793, 695869,  12545]))
[array([-9, 0, 1, 2, 3, 4], dtype=object), array([    20, 133735, 174099,  88969, 111571, 273437])]

In [6]:
# drop negative TRIPPURP (20 observations)
df = df.loc[df.TRIPPURP >= 0, :]
# drop negative trip miles. 
df = df.loc[df.TRPMILES >= 0, :]
# drop negative trip durations.
df = df.loc[df.TRVLCMIN >= 0, :]

In [7]:
# Create dummies for the dependent variables. 
# This automatically drop the two initial discrete variables from df.
df = pd.get_dummies(data=df, columns=["TRPTRANS","TRIPPURP"])

In [8]:
# drop the old variables
print(df.shape)
print(df.columns)
df.sample(n = 20)

(781811, 270)
Index(['CDIVMSAR', 'CENSUS_D', 'CENSUS_R', 'DRIVER', 'DRVRCNT', 'ENDTIME',
       'EDUC', 'GASPRICE', 'HBHTNRNT', 'HBHUR',
       ...
       'GEOID', 'TRPTRANS_0', 'TRPTRANS_1', 'TRPTRANS_2', 'TRPTRANS_3',
       'TRIPPURP_0', 'TRIPPURP_1', 'TRIPPURP_2', 'TRIPPURP_3', 'TRIPPURP_4'],
      dtype='object', length=270)

,CDIVMSAR,CENSUS_D,CENSUS_R,DRIVER,DRVRCNT,ENDTIME,EDUC,GASPRICE,HBHTNRNT,HBHUR,...,GEOID,TRPTRANS_0,TRPTRANS_1,TRPTRANS_2,TRPTRANS_3,TRIPPURP_0,TRIPPURP_1,TRIPPURP_2,TRIPPURP_3,TRIPPURP_4
151212,53,5,3,1,2,1808,4,230.2,40,C,...,37081016103,0,0,1,0,0,1,0,0,0
688433,33,3,2,1,2,958,4,230.1,5,C,...,55009010100,0,0,1,0,0,0,1,0,0
51925,53,5,3,1,2,830,5,228.4,5,T,...,45019002005,0,0,1,0,1,0,0,0,0
557327,22,2,1,1,2,1105,4,255.8,30,C,...,36063022902,0,0,1,0,0,0,0,0,1
179500,72,7,3,1,1,1505,3,211.8,20,T,...,48339690402,0,0,1,0,0,0,0,0,1
705502,92,9,4,1,4,1152,2,292.1,5,S,...,6073013605,0,0,1,0,0,0,0,0,1
568722,83,8,4,1,3,2200,2,236.5,5,R,...,56025001800,0,0,1,0,1,0,0,0,0
305148,72,7,3,1,3,1240,4,215.2,0,S,...,48113014205,0,0,1,0,0,0,1,0,0
482352,72,7,3,1,2,830,5,209.2,5,T,...,48491020203,0,0,1,0,1,0,0,0,0
523386,53,5,3,1,2,1703,5,236.2,5,T,...,45015020403,0,0,1,0,0,0,0,0,1
747193,72,7,3,1,4,1735,3,218.6,5,S,...,48121021404,0,0,1,0,0,0,0,0,1
150436,22,2,1,1,1,1335,3,236.1,30,R,...,36051030900,0,1,0,0,0,0,0,1,0
260985,33,3,2,1,2,1850,3,223.6,50,S,...,55009010202,0,0,1,0,0,0,0,0,1
86694,53,5,3,1,2,1500,4,218.4,5,R,...,37141920501,0,0,1,0,0,0,0,0,1
693041,34,3,2,1,2,1520,2,237.2,30,T,...,55135101100,0,0,1,0,0,0,0,0,1
643076,91,9,4,1,1,950,3,280.1,40,T,...,6065044807,0,1,0,0,0,1,0,0,0
290287,21,2,1,1,1,1540,3,235.7,5,T,...,36027050103,0,0,1,0,1,0,0,0,0
718896,53,5,3,1,1,2010,4,243.2,60,C,...,24043000601,0,0,1,0,1,0,0,0,0
588537,53,5,3,1,2,1315,3,223.5,5,T,...,37063001603,0,0,1,0,0,1,0,0,0
608332,92,9,4,1,3,930,5,281.9,5,S,...,6017030710,0,0,1,0,1,0,0,0,0

In [13]:
# Use HOUSEID and PERSONID to check redundancy.
print("Number of CENSUS_ID is: ", len(np.unique(df.CENSUS_ID)))
print("Number of GEOID is: ", len(np.unique(df.GEOID)))
print("Number of HHs is: ", len(np.unique(df.HOUSEID)))
print("Maximum persons in each HH: ", len(np.unique(df.PERSONID)))

Number of CENSUS_ID is:  32681
Number of GEOID is:  32681
Number of HHs is:  110565
Maximum persons in each HH:  10

## Clean independent variables

In [14]:
# continuous variables
# income
inc_dic = {1:10.0, 2:12.5, 3:20.0, 4:30.0, 5:42.5, 
          6:62.5, 7:87.5, 8:112.5, 9:137.5, 10:175.0, 11:200.0}
df.HHFAMINC.replace(to_replace = inc_dic, inplace = True)

# renter occupied housing ratio.
df = df.loc[df.HBHTNRNT >= 0, :]
rent_dic = {0:0.02, 5:0.1, 20:0.2, 30:0.3, 40:0.4, 50:0.5, 60:0.6, 70:0.7, 80:0.8, 90:0.9, 95:0.975}
df.HBHTNRNT.replace(to_replace=rent_dic, inplace = True)

# pop density
df = df.loc[df.HBPPOPDN >= 0, :]

# residential density
df = df.loc[df.HBRESDN >= 0, :]

In [15]:
# discrete variables
# educ
# 0: no reported; 1: high school and lower; 2: college and higher
educ_dic_1 = {-8:8, -7:8, -1:8, 1:9, 2:9, 3:10, 4:10, 5:10}
educ_dic_2 = {8:0, 9:1, 10:2}
_ = df.EDUC.replace(to_replace = educ_dic_1)
df['EDUC'] = _.replace(to_replace = educ_dic_2)

# HH_RACE
# 0: no report; 1: white; 2: others
race_dic_1 = {-8:8, -7:8, 1:9, 2:10, 3:10, 4:10, 5:10, 6:10, 97:10}
race_dic_2 = {8:0, 9:1, 10:2}
_ = df.HH_RACE.replace(to_replace=race_dic_1)
df['HH_RACE'] = _.replace(to_replace=race_dic_2)

# HOMEOWN
# 0: no report; 1: own; 2: rent
own_dic_1 = {-8:0, -7:0, 97:0}
df['HOMEOWN'] = df.HOMEOWN.replace(to_replace=own_dic_1)

In [16]:
# add variable: auto per capita
df['HHVEHCNT_P_CAP'] = df["HHVEHCNT"]/df["HHSIZE"]

In [35]:
# list of variables
# categorical 
categorical_variables = ["R_SEX_IMP", "EDUC", "HH_RACE", "HOMEOWN", "HBHUR"] # "MSACAT", "CENSUS_R", "URBAN", "RAIL" are removed

# numerical 
num_variables = ["R_AGE_IMP", "DRVRCNT", "HHSIZE", "HHFAMINC", "HBHTNRNT", "HBPPOPDN", "HBRESDN", 
                 "TRPMILES", "TRVLCMIN", "HHVEHCNT_P_CAP"]

targets = ["TRPTRANS_0", "TRPTRANS_1", "TRPTRANS_2", "TRPTRANS_3",
           "TRIPPURP_0", "TRIPPURP_1", "TRIPPURP_2", "TRIPPURP_3", "TRIPPURP_4", 
           "HHVEHCNT"]

#add index
all_variables = categorical_variables + num_variables + targets + ["CENSUS_ID", "GEOID"]
print(len(all_variables))

27

In [36]:
# one hot encoding
getEncoderList = df.copy(deep=True)
df_dummies = pd.get_dummies(data=getEncoderList[all_variables], columns=categorical_variables)
encoderList = list(set(pd.get_dummies(data=getEncoderList[all_variables], columns=categorical_variables).columns))
print(df_dummies.shape)

(781811, 35)

In [37]:
df_dummies # df with one-hot encoding.

,R_AGE_IMP,DRVRCNT,HHSIZE,HHFAMINC,HBHTNRNT,HBPPOPDN,HBRESDN,TRPMILES,TRVLCMIN,HHVEHCNT_P_CAP,...,HH_RACE_1,HH_RACE_2,HOMEOWN_0,HOMEOWN_1,HOMEOWN_2,HBHUR_C,HBHUR_R,HBHUR_S,HBHUR_T,HBHUR_U
0,67,3,3,87.5,0.2,750,300,5.244,15,1.666667,...,0,1,0,1,0,0,0,0,1,0
1,67,3,3,87.5,0.2,750,300,5.149,20,1.666667,...,0,1,0,1,0,0,0,0,1,0
2,66,3,3,87.5,0.2,750,300,84.004,120,1.666667,...,0,1,0,1,0,0,0,0,1,0
3,66,3,3,87.5,0.2,750,300,81.628,150,1.666667,...,0,1,0,1,0,0,0,0,1,0
4,28,3,3,87.5,0.2,750,300,2.250,15,1.666667,...,0,1,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781826,52,1,1,175.0,0.7,30000,17000,1.168,27,0.000000,...,1,0,0,1,0,0,0,0,0,1
781827,52,1,1,175.0,0.7,30000,17000,0.238,8,0.000000,...,1,0,0,1,0,0,0,0,0,1
781828,52,1,1,175.0,0.7,30000,17000,0.238,5,0.000000,...,1,0,0,1,0,0,0,0,0,1
781829,52,1,1,175.0,0.7,30000,17000,0.867,25,0.000000,...,1,0,0,1,0,0,0,0,0,1
781830,52,1,1,175.0,0.7,30000,17000,0.325,7,0.000000,...,1,0,0,1,0,0,0,0,0,1

In [38]:
df_dummies.columns

Index(['R_AGE_IMP', 'DRVRCNT', 'HHSIZE', 'HHFAMINC', 'HBHTNRNT', 'HBPPOPDN',
       'HBRESDN', 'TRPMILES', 'TRVLCMIN', 'HHVEHCNT_P_CAP', 'TRPTRANS_0',
       'TRPTRANS_1', 'TRPTRANS_2', 'TRPTRANS_3', 'TRIPPURP_0', 'TRIPPURP_1',
       'TRIPPURP_2', 'TRIPPURP_3', 'TRIPPURP_4', 'HHVEHCNT', 'CENSUS_ID',
       'GEOID', 'R_SEX_IMP_1', 'R_SEX_IMP_2', 'EDUC_1', 'HH_RACE_1',
       'HH_RACE_2', 'HOMEOWN_0', 'HOMEOWN_1', 'HOMEOWN_2', 'HBHUR_C',
       'HBHUR_R', 'HBHUR_S', 'HBHUR_T', 'HBHUR_U'],
      dtype='object')

## Identify Shared Census Tracts from NHTS and Image Data Sets
The main problem is that the census tract IDs from NHTS and the image folders are different. This block addresses this disparity.

In [21]:
# census tracts from Xiaohu's folder
root_name = "../../Documents/shenhao/sat_image_nhts/code/data_initial/osm/img"
print(os.getcwd())
dir_names = os.listdir(root_name)
print(len(dir_names))

# 
d10, d11 = util.digit_counts(dir_names)
print("10 digits census tracts: ", d10) # count the digits. 
print("11 digits census tracts: ", d11) # count the digits. 
# Note the standard tract ID is 11 digits. Need to add "0" to all the IDs with 10 digits.

/home/jtl/rachel_nhts/travel_modeling_nhts
35223
10 digits census tracts:  7989
11 digits census tracts:  27234

In [22]:
# 
standard_file_name_list = ['road_0.tif', 'road_1.tif', 'building_0.tif', 'building_1.tif']
num_channels = len(standard_file_name_list)

# replace old keys (10 digits) by new keys (11 digits)
old_keys = pd.Series(dir_names).astype(np.str)
new_keys = copy.copy(old_keys)
new_keys[old_keys.str.len()==10]='0'+old_keys[old_keys.str.len() == 10]
print(new_keys)

0        36103110300
1        06073010106
2        55087012400
3        50003970400
4        24033802204
            ...
35218    15003009300
35219    55025010501
35220    17031820101
35221    13051010802
35222    46011958803
Length: 35223, dtype: object

In [33]:
# find the matching keys between images and NHTS.
image_keys_list = list(new_keys) # Now images have 11 digits.
nhts_keys_list = list(df_dummies['CENSUS_ID']) # df.CENSUS_ID are all 11 digits.
shared_keys_list = list(set(nhts_keys_list) & set(image_keys_list)) # shared_keys_list.
print("Number of shared census tract IDs: ", len(shared_keys_list)) # shared keys from the two sets. 
df_dummies.head()

Number of shared census tract IDs:  32681

,R_AGE_IMP,DRVRCNT,HHSIZE,HHFAMINC,HBHTNRNT,HBPPOPDN,HBRESDN,TRPMILES,TRVLCMIN,HHVEHCNT_P_CAP,...,HH_RACE_1,HH_RACE_2,HOMEOWN_0,HOMEOWN_1,HOMEOWN_2,HBHUR_C,HBHUR_R,HBHUR_S,HBHUR_T,HBHUR_U
0,67,3,3,87.5,0.2,750,300,5.244,15,1.666667,...,0,1,0,1,0,0,0,0,1,0
1,67,3,3,87.5,0.2,750,300,5.149,20,1.666667,...,0,1,0,1,0,0,0,0,1,0
2,66,3,3,87.5,0.2,750,300,84.004,120,1.666667,...,0,1,0,1,0,0,0,0,1,0
3,66,3,3,87.5,0.2,750,300,81.628,150,1.666667,...,0,1,0,1,0,0,0,0,1,0
4,28,3,3,87.5,0.2,750,300,2.250,15,1.666667,...,0,1,0,1,0,0,0,0,1,0

In [24]:
# merge because the census tract IDs from the two sources do not match perfectly.
df_intersect = pd.merge(df_dummies, pd.Series(shared_keys_list, name = 'CENSUS_ID'), how = 'inner', on = 'CENSUS_ID')

# reindex
df_intersect.index = np.arange(df_intersect.shape[0])
print(df_intersect.shape)

(781811, 34)

In [25]:
print(df_intersect.shape)
df_intersect.head()

(781811, 34)

,R_AGE_IMP,DRVRCNT,HHSIZE,HHFAMINC,HBHTNRNT,HBPPOPDN,HBRESDN,TRPMILES,TRVLCMIN,HHVEHCNT_P_CAP,...,HH_RACE_1,HH_RACE_2,HOMEOWN_0,HOMEOWN_1,HOMEOWN_2,HBHUR_C,HBHUR_R,HBHUR_S,HBHUR_T,HBHUR_U
0,67,3,3,87.5,0.2,750,300,5.244,15,1.666667,...,0,1,0,1,0,0,0,0,1,0
1,67,3,3,87.5,0.2,750,300,5.149,20,1.666667,...,0,1,0,1,0,0,0,0,1,0
2,66,3,3,87.5,0.2,750,300,84.004,120,1.666667,...,0,1,0,1,0,0,0,0,1,0
3,66,3,3,87.5,0.2,750,300,81.628,150,1.666667,...,0,1,0,1,0,0,0,0,1,0
4,28,3,3,87.5,0.2,750,300,2.250,15,1.666667,...,0,1,0,1,0,0,0,0,1,0

In [26]:
df_intersect.columns

Index(['R_AGE_IMP', 'DRVRCNT', 'HHSIZE', 'HHFAMINC', 'HBHTNRNT', 'HBPPOPDN',
       'HBRESDN', 'TRPMILES', 'TRVLCMIN', 'HHVEHCNT_P_CAP', 'TRPTRANS_0',
       'TRPTRANS_1', 'TRPTRANS_2', 'TRPTRANS_3', 'TRIPPURP_0', 'TRIPPURP_1',
       'TRIPPURP_2', 'TRIPPURP_3', 'TRIPPURP_4', 'HHVEHCNT', 'CENSUS_ID',
       'R_SEX_IMP_1', 'R_SEX_IMP_2', 'EDUC_1', 'HH_RACE_1', 'HH_RACE_2',
       'HOMEOWN_0', 'HOMEOWN_1', 'HOMEOWN_2', 'HBHUR_C', 'HBHUR_R', 'HBHUR_S',
       'HBHUR_T', 'HBHUR_U'],
      dtype='object')

## Create aggregate and disaggregate dataframes.
Aggregate: Obtain mean value by aggregating over the census tracts. \
Disaggregate: Randomly sample one observation from the census tract. \
The disaggregate variables don't work well in regressions.

#### Create aggregate info

In [ ]:
# Choose only the census tracts with many observations. 
census_id_hist = copy.deepcopy(df_intersect).groupby("CENSUS_ID").aggregate(['count']).iloc[:,0]
large_census_tract_idx = census_id_hist[census_id_hist > 10]
print(len(large_census_tract_idx))
print(large_census_tract_idx)

In [ ]:
###  
df_intersect_large_tracts = df_intersect.set_index('CENSUS_ID').loc[large_census_tract_idx.index, :]

df_intersect_large_tracts['CENSUS_ID'] = df_intersect_large_tracts.index

df_intersect_large_tracts.index = np.arange(df_intersect_large_tracts.shape[0])

df_intersect_large_tracts

In [ ]:
# aggregate information. 
df_agg = df_intersect_large_tracts.groupby("CENSUS_ID").aggregate(['mean'])

In [ ]:
# create new names
df_agg_column_list = ['_'.join(df_agg.columns[i]) for i in range(df_agg.shape[1])]
print(df_agg_column_list)

In [ ]:
# change column names
df_agg.columns = df_agg_column_list

In [ ]:
df_agg

#### Create disaggregate info

In [ ]:
### 
df_disagg = df_intersect_large_tracts.drop_duplicates(subset = 'CENSUS_ID')

# reindex
df_disagg.index = df_disagg.CENSUS_ID

# drop the column
df_disagg.drop(columns = ["CENSUS_ID"], inplace=True)

In [ ]:
df_disagg

In [ ]:
# merge df_agg and df_disagg.
# keep the census_id vector. 
df_merged = df_disagg.merge(df_agg, how = 'left', left_index = True, right_index = True)

In [ ]:
print(df_merged.columns)
df_merged

In [ ]:
plt.hist(df_merged.HHVEHCNT_mean, bins = 20)
# Note: well, well...The result is not as continuous as I thought.

## Normalize continuous variables

In [ ]:
num_variables = ["R_AGE_IMP", "DRVRCNT", "HHSIZE", "HHFAMINC", "HHVEHCNT", "TRPMILES", "TRVLCMIN", 
                 "HBHTNRNT", "HBPPOPDN", "HBRESDN", "HHVEHCNT_P_CAP", 
                 "R_AGE_IMP_mean", "DRVRCNT_mean", "HHSIZE_mean", "HHFAMINC_mean", "HHVEHCNT_mean", "TRPMILES_mean", "TRVLCMIN_mean", 
                 "HBHTNRNT_mean", "HBPPOPDN_mean", "HBRESDN_mean", "HHVEHCNT_P_CAP_mean", 
                 "TRPTRANS_0_mean", "TRPTRANS_1_mean", "TRPTRANS_2_mean", "TRPTRANS_3_mean", 
                 "TRIPPURP_0_mean", "TRIPPURP_1_mean", "TRIPPURP_2_mean", "TRIPPURP_3_mean", "TRIPPURP_4_mean"
                ]

num_variables_norm = [num_variable+'_norm' for num_variable in num_variables]

In [ ]:
### normalization for continous variables.
# It is improvable. Tried Min Max scaler. We should try more. 

from sklearn.preprocessing import StandardScaler

for idx in range(len(num_variables)):
    num_variable = num_variables[idx]
    scaler = StandardScaler()
    # 100K
    single_normalized = scaler.fit_transform(df_merged.loc[:,num_variable].values.reshape(-1,1).astype(np.float32))
    # attach new var
    num_variable_norm = num_variables_norm[idx]
    df_merged[num_variable_norm] = single_normalized

In [ ]:
for c in df_merged.columns:
    print(c)

## Read image data

In [ ]:
# create a list of census_tract_id that exist in NHTS 
# but make them follow the same format as the raw image folder (10 digits and 11 digits)
folder_new_id_list = list(df_merged.index)
folder_old_id_list = []
for id_ in folder_new_id_list:
    if id_[0] == '0':
        folder_old_id_list.append(id_[1:])
    else:
        folder_old_id_list.append(id_) # match up to the folder names...

In [ ]:
print(len(folder_old_id_list))
print(folder_old_id_list[:10])

In [ ]:
# the satellite images with RPG
rgb_path_name = "../shenhao/sat_image_nhts/code/data_initial/satellite/img"
dir_names_ = os.listdir(rgb_path_name)
d10,d11 = util.digit_counts(dir_names_,SAT=True)
print(d10,d11)
print(dir_names_[:10])

In [ ]:
# initialize black and white images
file_size = (224, 224) # default sizes in all CNN architectures
image_array = np.zeros((len(folder_old_id_list), num_channels, file_size[0], file_size[1])) # default: black images

In [ ]:
sys.getsizeof(image_array) # 29GB.

In [ ]:
# read the images. 
empty = 0
non_empty = 0

for folder_name_idx in np.arange(len(folder_old_id_list)):
    if folder_name_idx%500==0:
        print(folder_name_idx)
    for file_name_idx in np.arange(len(standard_file_name_list)):
        full_file_name = root_name+'/'+folder_old_id_list[folder_name_idx]+'/'+standard_file_name_list[file_name_idx]
        img = cv2.imread(full_file_name, cv2.IMREAD_UNCHANGED)
        if img is None:
            empty += 1
            pass # default is black images...so when images do not exist. Keep the zeros
        else:
            non_empty += 1
            image_array[folder_name_idx, file_name_idx, :, :] = cv2.resize(img, file_size).astype(np.uint8)

### 
print("Black and white image (empty): ", empty)
print("Black and white image (non_empty): ", non_empty)

In [ ]:
# initialize the RGB images
file_size = (224, 224) 
rgb_image_array = np.zeros((len(folder_old_id_list), 3, file_size[0], file_size[1]))

In [ ]:
# read the images.
empty = 0
non_empty = 0

for folder_name_idx in np.arange(len(folder_old_id_list)):
    if folder_name_idx%500==0:
        print(folder_name_idx)
    full_file_name = rgb_path_name+'/wms'+folder_old_id_list[folder_name_idx]+'.jpg'
    img = cv2.imread(full_file_name, cv2.IMREAD_UNCHANGED)
    if img is None:
        empty += 1
        pass # default is black images...so when images do not exist. Keep the zeros
    else:
        non_empty += 1
        rgb_image_array[folder_name_idx, :, :, :] = np.moveaxis(cv2.resize(img, file_size), 2, 0).astype(np.uint8)

### 
print("RGB images (empty): ", empty)
print("RGB images (non_empty): ", non_empty)

In [ ]:
# plt.figure(figsize = (4,4))
util.imshow(image_array[100, 1, :, :][:,:,np.newaxis].astype('float32'))

In [ ]:
util.imshow(np.moveaxis(rgb_image_array[10,:,:,:], 0, 2).astype("uint8"))

In [ ]:
print("NHTS and Image data match: ", df_intersect.shape[0] == image_array.shape[0])
print(image_array.shape)

## Create BE variables: 3Ds
Create 3Ds from the images

In [ ]:
# Design. use road network average for design
design = np.mean(image_array[:, 0, :, :] + image_array[:, 1, :, :], axis = (1,2))
print(design.shape)

In [ ]:
# Density. use building layers' average for density
density = np.mean(image_array[:, 2, :, :] + image_array[:, 3, :, :], axis = (1,2))
print(density.shape)

In [ ]:
# Diversity. use the entropy formula to compute diversity. 
building_density_1 = np.mean(image_array[:, 2, :, :], axis=(1,2))[:, np.newaxis]
building_density_2 = np.mean(image_array[:, 3, :, :], axis=(1,2))[:, np.newaxis]
building_densities = np.concatenate([building_density_1, building_density_2], axis = 1)

from scipy.stats import entropy
diversity = []
for i in range(building_densities.shape[0]):
    if building_densities[i, 0]*building_densities[i, 1] == 0:
        diversity_i = 0
    else:
        diversity_i = entropy(building_densities[i,:], base = 2)
    diversity.append(diversity_i)

diversity = np.array(diversity)
print(diversity.shape)

In [ ]:
# create BE matrix
BE = np.vstack([density, diversity, design]).T

# 0-1 normalize
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
BE = scaler.fit_transform(BE)
plt.boxplot(BE)

# dataframe
BE_df = pd.DataFrame(BE, columns = ['density', 'diversity', 'design'], index = df_merged.index)

# df_merged = pd.con
df_merged = pd.concat([df_merged, BE_df], axis = 1)

In [ ]:
df_merged

## Save Data Sets

In [ ]:
# save the image arrays 1
np.save("data_process/image_array_bw_tract_large", image_array)

In [ ]:
# 2
np.save("data_process/image_array_rgb_tract_large", rgb_image_array)

In [ ]:
# save the full dataframe.
df_merged.to_csv("data_process/df_merged_tract_large_1.csv")

In [ ]:
df_test = pd.read_csv("../../Documents/shenhao/sat_image_nhts/code/df_merged_tract_large.csv")